const declarations = require("./declarations");

module.exports = [    
    declarations.getRunningModel(declarations.Type.CalmRun, null,declarations.Pace.Low, 15 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null,declarations.Pace.Low, 15 * 60),
    declarations.getRunningModel(declarations.Type.CalmRun, null,declarations.Pace.Low, 15 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 2000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 1000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null,declarations.Pace.Low, 20 * 60),
    declarations.getRunningModel(declarations.Type.CalmRun, null,declarations.Pace.Low, 20 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 2000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 2000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 1000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 1000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 3000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.FastRun, null,declarations.Pace.High, 5 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 3000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null,declarations.Pace.Low, 30 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null,declarations.Pace.Low, 30 * 60),
    declarations.getRunningModel(declarations.Type.NormalRun, null,declarations.Pace.Normal, 10 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null,declarations.Pace.Low, 15 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null,declarations.Pace.Low, 30 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 3000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 3000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null,declarations.Pace.Low, 45 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null,declarations.Pace.Low, 45 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null,declarations.Pace.Low, 20 * 60),
    declarations.getRunningModel(declarations.Type.LongRun, 3000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null,declarations.Pace.Low, 45 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null,declarations.Pace.Normal, 25 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null,declarations.Pace.Low, 45 * 60),
    declarations.getRunningModel(declarations.Type.NormalRun, null,declarations.Pace.Normal, 25 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 4000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 3000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null,declarations.Pace.Normal, 20 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 3000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 1000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 4000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null,declarations.Pace.Low, 50 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null,declarations.Pace.Normal, 25 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null,declarations.Pace.Low, 50 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CheckRun, 5000, declarations.Pace.Low, null)
].map((model, index) => {
    return { day: index, ...model };
});
