const declarations = require("./declarations");

module.exports = [    
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 24 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 24 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.Normal, 19),
    declarations.getRunningModel(declarations.Type.RecoveryRun, null, declarations.Pace.Low, 20 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 28 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 28 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 28 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.Normal, 24 * 60),
    declarations.getRunningModel(declarations.Type.RecoveryRun, null, declarations.Pace.Low, 20 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 34 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.Normal, 28 * 60),
    declarations.getRunningModel(declarations.Type.RecoveryRun, null, declarations.Pace.Low, 20 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 44 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 44 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.Normal, 34 * 60),
    declarations.getRunningModel(declarations.Type.RecoveryRun, null, declarations.Pace.Low, 20 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.Low, 25 * 60),
    declarations.getRunningModel(declarations.Type.RecoveryRun, null, declarations.Pace.Low, 20 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.Low, 30 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.FastRun, null, declarations.Pace.High, 20 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 44 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.Normal, 40 * 60),
    declarations.getRunningModel(declarations.Type.RecoveryRun, null, declarations.Pace.Low, 30 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.RecoveryRun, null, declarations.Pace.Low, 25 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.RecoveryRun, null, declarations.Pace.Low, 30 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.Normal, 30 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.RecoveryRun, null, null, 20 * 60),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 45 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 45 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 45 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.Normal, 30 * 60),
    declarations.getRunningModel(declarations.Type.RecoveryRun, null, declarations.Pace.Low, 30 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 45 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.Normal, 32),
    declarations.getRunningModel(declarations.Type.RecoveryRun, null, declarations.Pace.Low, 20 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 30 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 30 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.Normal, 20 * 60),
    declarations.getRunningModel(declarations.Type.RecoveryRun, null, declarations.Pace.Low, 20 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 45 * 60),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 45 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 45 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.Normal, 30 * 60),
    declarations.getRunningModel(declarations.Type.RecoveryRun, null, declarations.Pace.Low, 20 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 45 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.Normal, 35 * 60),
    declarations.getRunningModel(declarations.Type.RecoveryRun, null, declarations.Pace.Low, 30 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 47 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 47 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.Normal, 35 * 60),
    declarations.getRunningModel(declarations.Type.RecoveryRun, null, declarations.Pace.Low, 20 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 47 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 47 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 47 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.Normal, 35 * 60),
    declarations.getRunningModel(declarations.Type.RecoveryRun, null, declarations.Pace.Low, 20 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 50 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.FastRun, null, declarations.Pace.High, 20 * 60),
    declarations.getRunningModel(declarations.Type.RecoveryRun, null, declarations.Pace.Low, 20 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 50 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 50 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.Normal, 35 * 60),
    declarations.getRunningModel(declarations.Type.RecoveryRun, null, declarations.Pace.Low, 32 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 50 * 60),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 55 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 55 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.FastRun, null, declarations.Pace.High, 30 * 60),
    declarations.getRunningModel(declarations.Type.RecoveryRun, null, declarations.Pace.Low, 30 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 50 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.Normal, 40 * 60),
    declarations.getRunningModel(declarations.Type.RecoveryRun, null, declarations.Pace.Low, 30 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 45 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 55 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.Normal, 30 * 60),
    declarations.getRunningModel(declarations.Type.RecoveryRun, null, declarations.Pace.Low, 40 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 60 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 60 * 60)
].map((model, index) => {
    return { day: index, ...model };
});
