const declarations = require("./declarations");

module.exports = [    
    declarations.getRunningModel(declarations.Type.CalmRun, 5 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.FastRun, 1 * 1000, declarations.Pace.High, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 5 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 1 * 1000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 8 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 6 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.FastRun, 1 * 1000, declarations.Pace.High, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 6 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 2 * 1000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 8 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 6 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.FastRun, 1 * 1000, declarations.Pace.High, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 6 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 3 * 1000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 9 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 6 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.FastRun, 1 * 1000, declarations.Pace.High, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 6 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 4 * 1000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 13 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 5 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.FastRun, 1 * 1000, declarations.Pace.High, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 5 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 1 * 1000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 9 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 6 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.FastRun, 1 * 1000, declarations.Pace.High, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 6 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 2 * 1000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 8 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 6 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.FastRun, 1 * 1000, declarations.Pace.High, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 8 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 3 * 1000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 14 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 8 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.FastRun, 1 * 1000, declarations.Pace.High, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 8 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 4 * 1000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 16 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 8 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.FastRun, 2 * 1000, declarations.Pace.High, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 9 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 4 * 1000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 19 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 8 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.FastRun, 2 * 1000, declarations.Pace.High, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 9 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 4 * 1000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 21 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 6 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.FastRun, 2 * 1000, declarations.Pace.High, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 6 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 3 * 1000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 16 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 8 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.FastRun, 2 * 1000, declarations.Pace.High, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 9 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 4 * 1000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 19 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 9 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.FastRun, 2 * 1000, declarations.Pace.High, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 9 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 4 * 1000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 22 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 9 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.FastRun, 2 * 1000, declarations.Pace.High, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 8 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 4 * 1000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 26 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 9 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.FastRun, 2 * 1000, declarations.Pace.High, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 9 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 5 * 1000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 29 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 9 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.FastRun, 2 * 1000, declarations.Pace.High, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 13 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 5 * 1000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 32 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 6 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.FastRun, 2 * 1000, declarations.Pace.High, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 8 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 4 * 1000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 21 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 2 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.FastRun, 1 * 1000, declarations.Pace.High, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 6 * 1000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 2 * 1000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 16 * 1000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.Marathon, 42 * 1000, declarations.Pace.Low, null),
].map((model, index) => {
    return { day: index, ...model };
});
