const declarations = require("./declarations");

module.exports = [    
    declarations.getRunningModel(declarations.Type.CalmRun, 2000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 1000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 30 * 60),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 20 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 2000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.FastRun, 1000, declarations.Pace.High, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.Normal, 30 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 2000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 4000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.FastRun, 1000, declarations.Pace.High, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 3000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 2000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 30 * 60),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 20 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 6000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 3000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.Normal, 30 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 4000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 6000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.FastRun, 3000, declarations.Pace.High, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 8000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 35 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 30 * 60),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.Normal, 30 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.Low, 30 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 40 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 9000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.Normal, 30 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 40 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 45 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.RecoveryRun, null, declarations.Pace.Low, 20 * 60),
    declarations.getRunningModel(declarations.Type.LongRun, 10000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 55 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.High, 25 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 55 * 60),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.Low, 45 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.LongRun, 10000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 5000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 20 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, 10000, declarations.Pace.Low, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 6000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, 6000, declarations.Pace.Normal, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 60 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.NormalRun, null, declarations.Pace.Normal, 35 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.CalmRun, null, declarations.Pace.Low, 50 * 60),
    declarations.getRunningModel(declarations.Type.Rest, null, null, null),
    declarations.getRunningModel(declarations.Type.Marathon10, 10000, null, null),
].map((model, index) => {
    return { day: index, ...model };
});
